### ISSUE TITLE
False positives when comparing maps

### ISSUE THREAD

**Issue by juliekoubova** [planttheidea/fast-equals#23]
deepEqual(
      new Map([ ['key1', 'foo'], ['key2', 'bar'] ]),
      new Map([ ['key1', 'bar'], ['key2', 'foo'] ])
    ) === true

**Comment by planttheidea** [comment]
Good catch! It seems so obvious looking at the code now, I was just checking "does this key exist in the other, and does this value exist in the other" ... not aligning key to value.

I should have a fix out shortly.

**Comment by planttheidea** [comment]
Ok I've added this example as a case in the test suite, and this should be fixed in `1.6.2`. Let me know if you have any further issues!
