### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by ehmicky** [planttheidea/fast-equals#25]
Hi there, great library, thanks for that work!

Would you consider adding git tags to every release? This would create GitHub releases. GitHub releases are great to be updated about new versions and can be used by RSS readers. 

I can see I've already bugged you about this on another library of yours: [`moize`](https://github.com/planttheidea/moize/issues/99). Great functional utilities (functional JavaScript is awesome), keep up the good work!

**Comment by planttheidea** [comment]
Haha indeed you have, and I'm glad you did! I use `release-it` now for all my releases, so yes going forward expect tags and releases for all the things.

**Comment by planttheidea** [comment]
Closing now that `release-it` is used for releases.
