### ISSUE TITLE
Reproducible build instructions

### ISSUE THREAD

**Issue by luckyrat** [planttheidea/fast-equals#26]
To reproduce the build for this library...

````
git clone https://github.com/planttheidea/fast-equals.git
cd fast-equals

# In future this would be a git tag assuming #25 gets implemented
git checkout 3307586bb975871f5f5cd9a5705c720ac9f79af0

# The project contains a yarn lock file but not an npm lock file.
# Since some build dependencies have changed to result in a different
# minified output we must therefore use yarn rather than npm
yarn install

# "npm run-script build" works too but you already have yarn so...
yarn run build

# To get an exact checksum match with the versions released on 
# npm, it may be necessary to change line endings. For example, 
# on Linux you might run:
unix2dos dist/fast-equals.min.js

# Now something like this will give a checksum:
sha256sum dist/fast-equals.min.js
````

This procedure is necessary for 3rd parties to verify the integrity of the distributed files. For example, Mozilla can perform this as part of their routine security checks of any Firefox add-on that includes this library (I've written these guidelines to help the Mozilla reviewers since I included it in [Kee](https://github.com/kee-org/browser-addon/)).

I've only verified that this works for the min.js version of the library but I suspect the other distributed files will be verifiable in the same fashion.

**Comment by planttheidea** [comment]
Forgive me, I'm kind of confused. Is this an issue? Is this documentation you want included in the `README`? This seems more like a statement than some sort of actionable request.

**Comment by luckyrat** [comment]
Yeah it's basically an FYI. I think it needs to be documented/recorded somewhere (since it's not obvious from reading the current README file) but totally up to you whether you prefer to incorporate it into the README, keep it here as a (presumably closed?) issue, move to some other source of documentation, or whatever.

**Comment by planttheidea** [comment]
No worries. Based on this feedback, I've incorporated a new `BUILD.md` file that details this into the `2.0.0` release I'll be doing within the next few days. I'll close once that is released.

**Comment by planttheidea** [comment]
Instructions are now available at [BUILD.md](https://github.com/planttheidea/fast-equals/blob/master/BUILD.md)
