### ISSUE TITLE
Can't tree shaking properly in webpack

### ISSUE THREAD

**Issue by foray1010** [planttheidea/fast-equals#29]
webpack uses `browser` over `main` or `module`, but `browser` build cannot be tree shaked
ref: https://github.com/webpack/webpack/issues/4674

I saw there are some solutions:
1. https://github.com/webpack/webpack/issues/4674#issuecomment-355853969
2. rename `browser` to `unpkg` (although I am not sure if it is a good choice)

What is your opinion on this? @planttheidea

**Comment by planttheidea** [comment]
Why not just use the webpack option specifically for this?

https://webpack.js.org/configuration/resolve/#resolvealiasfields

**Comment by foray1010** [comment]
because I am developing a library using `fast-equals`, it is a sub-dependency that not visible directly by user, so I would like to provide a good default setting

**Comment by planttheidea** [comment]
Well it's generally considered poor practice to bundle dependencies with your library build (let the consumer's build systems to that resolution).

That said, if you really want this, you can always require the specific build file.

`import { deepEqual } from 'fast-equals/dist/fast-equals.min.js';`

It's what the `main` field resolves to, so specifying it directly should give you what you want.

**Comment by foray1010** [comment]
things may get dirty because I will need to export cjs and esm build, but properly can be solved by <https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping>, thank you for the advise!
