### ISSUE TITLE
createCustomEqual's meta argument - how exactly is it meant to be used?

### ISSUE THREAD

**Issue by Slapbox** [planttheidea/fast-equals#37]
In the example `meta` is defined at a higher scope and not passed into the custom equality check function, so I'm wondering what the `meta` arg that's passed into the function is exactly.

The example section here: https://github.com/planttheidea/fast-equals#createcustomequal

Specifically I'm confused by the purpose of `meta` in the following line:

```js
return (objectA, objectB, meta) => {
```

**Comment by planttheidea** [comment]
It seems my example needs updating! The `meta` property is something that can be passed in (and optionally passed through) to the comparing function. The example in the documentation should read:

```js
import { createCustomEqual } from 'fast-equals';

const isDeepEqualOrFooMatchesMeta = createCustomEqual(
  (deepEqual) => (objectA, objectB, meta) => (
    objectA.foo === meta ||
    objectB.foo === meta ||
    deepEqual(objectA, objectB, meta)
  )
);

const objectA = { foo: 'bar' };
const objectB = { foo: 'baz' };
const meta = 'bar';

// Notice `meta` is passed to `isDeepEqualOrFooMatchesMeta`
console.log(isDeepEqualOrFooMatchesMeta(objectA, objectB, meta)); // true
```

It can be whatever you want it to be, but its purpose is to be an additional datapoint outside of the two objects being compared. The example above is contrived, but a more practical example is its use internally for `circularDeepEqual` / `circularShallowEqual`; in these methods, the `meta` property is a cache of previously-seen objects, which allows validation of circular objects. Admittedly, this is very rare use-case, but it can be useful if you have a need for truly bespoke equality comparisons.

I'll update the documentation to be correct. Sorry for the confusion!

**Comment by Slapbox** [comment]
Thanks for the clarification - don't apologize though! 

If anything I owe you, big time. Thanks for your phenomenal work!
