### ISSUE TITLE
Maps comparison : same key/value can be used multiple times

### ISSUE THREAD

**Issue by g-traub** [planttheidea/fast-equals#58]
The first value in `mapB` in the example above is used twice, since the keys are equal.
```js
const mapA = new Map([[{b: 'c'}, 2],[{b: 'c'}, 2]])
const mapB = new Map([[{b: 'c'}, 2], ['foo', 'different']])

deepEqual(mapA, mapB)) // true
```
Example here : https://runkit.com/g-traub/map-keys-comparison

Using sameValueZero comparison would fix this, but maybe change the current behaviour too much ?
With deep comparison, we would need to make sure the same key/value pair can't be used multiple times.

**Comment by planttheidea** [comment]
This is definitely an issue. Investigating now.

**Comment by planttheidea** [comment]
The issue actually appears to be because the value from `mapA` always find a match in `mapB` (the first value). I have a setup that uses a local cache to avoid matching previously-matched values, should have a change up shortly.

**Comment by planttheidea** [comment]
Also, same issue exists on `Set`. Eesh!

**Comment by planttheidea** [comment]
FYI I've added you as a collaborator on the project so that you can review the fix.
