### ISSUE TITLE
Use generic types

### ISSUE THREAD

**Issue by SebastianPodgajny** [planttheidea/fast-equals#70]
Hi,

Currently if you use `deepEqual` inside rxjs distinctUntilChanged type will be casted to any
<img width="414" alt="image" src="https://user-images.githubusercontent.com/21180501/160624953-ea56cdb5-702c-482e-989d-c06d32769ee2.png">

to fix this issue you can use generic types instead of `any`
```typescript
export declare function circularDeepEqual<A, B>(objectA: A, objectB: B): boolean;
export declare function circularShallowEqual<A, B>(objectA: A, objectB: B): boolean;
export declare function deepEqual<A, B>(objectA: A, objectB: B): boolean;
export declare function shallowEqual<A, B>(objectA: A, objectB: B): boolean;
export declare function sameValueZeroEqual<A, B>(objectA: A, objectB: B): boolean;
```
with this change type is preserved as expected 
<img width="414" alt="image" src="https://user-images.githubusercontent.com/21180501/160624906-4502c0b8-76dc-44d1-9ef4-f2c2c085f53f.png">

**Comment by planttheidea** [comment]
Fixed with release of `3.0.1`. Thanks for the contribution!
