### ISSUE TITLE
Broken circularDeepEqual

### ISSUE THREAD

**Issue by nin-jin** [planttheidea/fast-equals#77]
v3.0.2

```ts
const x = [1]
const left =  [{ a: [1], b:  x  }]
const right = [{ a:  x,  b: [1] }]

// should returns true, but returns false
circularDeepEqual( left, right )
```

[Sandbox](https://eval.js.hyoo.ru/#!code=const%20compare%20%3D%20%24mol_import.module%28%0A%09'https%3A%2F%2Fesm.sh%2Ffast-equals'%0A%29.circularDeepEqual%0A%0Aconst%20x%20%3D%20%5B1%5D%0Aconst%20left%20%3D%20%20%5B%7B%20a%3A%20%5B1%5D%2C%20b%3A%20%20x%20%20%7D%5D%0Aconst%20right%20%3D%20%5B%7B%20a%3A%20%20x%2C%20%20b%3A%20%5B1%5D%20%7D%5D%0A%0A%24mol_assert_equal%28%0A%09compare%28%20left%2C%20right%20%29%2C%0A%09true%2C%0A%29)

**Comment by planttheidea** [comment]
Ah yes, I can see how this would happen, because I have a pretty naive setup for the circular reference checks. I have a fix for this working locally, which is based on [how `lodash` handles their circular reference checks](https://github.com/lodash/lodash/blob/master/.internal/equalObjects.js#L40). I need to fix some tests, and technically this creates a breaking change, because it requires switching support from `WeakSet` to `WeakMap` ... but this should be a _very_ rare case, so I'll need to think of how rigidly adherent to semver I should be.

**Comment by planttheidea** [comment]
This should be resolved in version `3.0.3`. Let me know if you have any more issues!

**Comment by nin-jin** [comment]
```js
const x = [1]; x.push(x)
const left =  [ [1,x],    x  ]
const right = [    x,  [1,x] ]

// should returns true, but returns false
circularDeepEqual( left, right ),
```

[Sandbox](https://eval.js.hyoo.ru/#!code=const%20compare%20%3D%20%24mol_import.module%28%0A%09'https%3A%2F%2Fesm.sh%2Ffast-equals'%0A%29.circularDeepEqual%0A%0Aconst%20x%20%3D%20%5B1%5D%3B%20x.push%28x%29%0Aconst%20left%20%3D%20%20%5B%20%5B1%2Cx%5D%2C%20%20%20%20x%20%20%5D%0Aconst%20right%20%3D%20%5B%20%20%20%20x%2C%20%20%5B1%2Cx%5D%20%5D%0A%0A%24mol_assert_equal%28%0A%09compare%28%20left%2C%20right%20%29%2C%0A%09true%2C%0A%29)

**Comment by planttheidea** [comment]
Oy, it looks like I was a bit optimistic in my fix for circular objects. I've done a lot more digging, and I have a solution, but because it involved a decent refactor I'm going to take the opportunity to introduce some breaking changes I've been sitting on for a while. I'll need to clean things up, but I'll try to have a v4 out with the proper fix within the next week.

**Comment by planttheidea** [comment]
Alright, version `4.0.0` has been released, and it should handle the above use-case as well, so I'm re-closing. Hope this new version works better for your needs!

**Comment by nin-jin** [comment]
Good job. I have added `fast-equals` to benchmark:
[![image](https://user-images.githubusercontent.com/442988/172071289-c0f37229-a063-41f2-addb-2a17a7b5b729.png)](https://perf.js.hyoo.ru/#!prefixes=%5B%22const%20compare%20%3D%20%24mol_import.module%28%5Cn%5Ct'https%3A%2F%2Fesm.sh%2Fmol_compare_deep'%5Cn%29.default.%24mol_compare_deep%22%2C%22const%20compare%20%3D%20%24mol_import.module%28%5Cn%5Ct'https%3A%2F%2Fesm.sh%2Ffast-equals'%5Cn%29.circularDeepEqual%22%2C%22const%20compare%20%3D%20%24mol_import.module%28%5Cn%5Ct'https%3A%2F%2Fesm.sh%2Fdeep-eql'%5Cn%29.default%22%2C%22const%20compare%20%3D%20%24mol_import.module%28%5Cn%5Ct'https%3A%2F%2Fesm.sh%2Fdeep-equal'%5Cn%29.default%22%5D/prefix=const%20make%20%3D%20i%20%3D%3E%20%7B%0A%0A%09const%20next%20%3D%20%7B%0A%09%09obj%3A%20%7B%0A%09%09%09x%3A%20new%20Map%28%5B%5B%20el%2C%20%2F3%2F%20%5D%5D%29%2C%0A%09%09%09y%3A%20new%20Set%28%5B%20new%20Date%281%29%20%5D%29%2C%0A%09%09%7D%2C%0A%09%09val%3A%20%5B%20true%2C%201%2C%20'2'%2C%20i%20%5D%2C%0A%09%7D%0A%0A%09next.val.push%28%20next%2C%20next.obj%2C%20next.val%20%29%0A%0A%09return%20next%0A%7D%0A%0Alet%20el%20%3D%20document.createElement%28%20'div'%20%29%0Alet%20base%20%3D%20make%28-1%29%0Alet%20res%20%3D%20true/sources=%5B%22const%20next%7B%23%7D%20%3D%20make%28%7B%23%7D%29%5Cnres%20%26%26%3D%20compare%28%20base%2C%20next%7B%23%7D%20%29%5Cnres%20%7C%7C%3D%20compare%28%20base.obj%2C%20next%7B%23%7D.obj%20%29%5Cnbase%20%3D%20next%7B%23%7D%22%2C%22const%20next%7B%23%7D%20%3D%20make%28%7B%23%7D%29%5Cnres%20%26%26%3D%20compare%28%20base%2C%20next%7B%23%7D%20%29%5Cnres%20%7C%7C%3D%20compare%28%20base.obj%2C%20next%7B%23%7D.obj%20%29%5Cnbase%20%3D%20next%7B%23%7D%22%2C%22const%20next%7B%23%7D%20%3D%20make%28%7B%23%7D%29%5Cnres%20%26%26%3D%20compare%28%20base%2C%20next%7B%23%7D%20%29%5Cnres%20%7C%7C%3D%20compare%28%20base.obj%2C%20next%7B%23%7D.obj%20%29%5Cnbase%20%3D%20next%7B%23%7D%22%2C%22const%20next%7B%23%7D%20%3D%20make%28%7B%23%7D%29%5Cnres%20%26%26%3D%20compare%28%20base%2C%20next%7B%23%7D%2C%20%7B%20strict%3A%20true%20%7D%20%29%5Cnres%20%7C%7C%3D%20compare%28%20base.obj%2C%20next%7B%23%7D.obj%2C%20%7B%20strict%3A%20true%20%7D%20%29%5Cnbase%20%3D%20next%7B%23%7D%22%5D/postfix=%24mol_assert_ok%28%20res%20%29%0A%24mol_assert_not%28%20compare%28%20make%281%29%2C%20make%282%29%20%29%20%29%0A%24mol_assert_ok%28%20compare%28%20make%281%29%2C%20make%281%29%20%29%20%29)
