### ISSUE TITLE
link to jsPerf in docs

### ISSUE THREAD

**Issue by josh-sachs** [planttheidea/fast-equals#9]
Just a suggestion - would be cool to include a jsPerf link next to the benchmarks.

**Comment by planttheidea** [comment]
The benchmarks were run on Node 8.9.4 using the script in the benchmark folder, testing a variety of uses cases for both accuracy and speed. As such, there is no jsperf to link to. If you wanted to create a separate jsperf for these purposes, I always happily  accept PRs!
