### ISSUE TITLE
Incorrect object with symbols as keys comparison

### ISSUE THREAD

**Issue by rafde** [planttheidea/fast-equals#93]
https://codesandbox.io/s/hidden-leaf-jzrnmu?file=/src/index.js

```js
const obj1 = {
  [Symbol.for("hi")]: 1
};
const obj2 = {
  [Symbol.for("hi")]: 2
};

console.log('Should be false', deepEqual(obj1, obj2))
```

**Comment by planttheidea** [comment]
This is similar to #91, in that non-traditional keys (Symbols, getters on class instances, etc.) are basically ignored. As mentioned in that issue, there is planned work to support a "strict" version of equality comparison much like [`copyStrict` from `fast-copy`](https://www.npmjs.com/package/fast-copy#copystrict), and this use-case shall be supported there as well.

**Comment by planttheidea** [comment]
I should have mentioned, in the meantime before this is released, you can [create a custom equality comparator](https://github.com/planttheidea/fast-equals/blob/master/recipes/non-standard-properties.md) to solve your use-case.

**Comment by rafde** [comment]
@planttheidea strictDeepEqual worked. Thank

**Comment by planttheidea** [comment]
Excellent! I'll be letting this sit in beta for another day or two, but expect it to be out of beta by next week. Thanks for following up!

**Comment by planttheidea** [comment]
`5.0.0` has been published with support for symbol checks via `strict*Equal` comparators. If you have any more issues, please let me know!
