### ISSUE TITLE
Please provide info about supported `node` versions

### ISSUE THREAD

**Issue by Semigradsky** [planttheidea/fast-equals#96]
Thank you for great package!

There is no `engines` field in `package.json` 😢 

Can this package be used as replacement of `fast-deep-equal` on ~old~ mature projects or not?

**Comment by planttheidea** [comment]
Good catch! I can provide an `engines` field; I'll need to do a little research to be as precise as possible, but it should be a fairly old version. The CommonJS build used is back to ES5, and while there are ES2015 requirements for certain "out of the box" pieces (example: regexp checking for `flags`, `WeakMap` used as the default circular cache), it is possible to override that and provide fallback versions for older runtimes.

**Comment by planttheidea** [comment]
Alright, `5.0.0-beta.4` has been published and includes `engines` definition. I went with the lowest version necessary to support _all_ features out of the box, and `RegExp.prototype.flags` was added to NodeJS in `6.0.0` [per MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/flags#browser_compatibility). All other support pieces (`WeakMap` / `Map` / `Set`) were much lower, `0.12.0`.

That said, it is also possible to support older engines if you use `createCustomEqual` to override some of those values. For example, if you want to overcome the `RegExp.prototype.flags` requirement, you can [provide a custom method which will work back to ES5](https://github.com/planttheidea/fast-equals/blob/v5/recipes/legacy-regexp-support.md).

Let me know if this works as you expect ... its the first time adding `engines` to one of my packages.

**Comment by Semigradsky** [comment]
👍 I tried beta.5 on Node.js v6 - looks great.

> RegExp.prototype.flags was added to NodeJS in 6.0.0

As I see it can be easily ponyfilled https://github.com/es-shims/RegExp.prototype.flags/blob/main/implementation.js

**Comment by planttheidea** [comment]
Yup, definitely also something easily filled. I was just providing that information in case fills were not possible for your setup.

Thanks for the quick feedback!

**Comment by planttheidea** [comment]
`5.0.0` has been published with `engines` to provide node version support. If you have any more issues, let me know!
